version: '3.8'

services:
  postgres:
    image: postgres
    container_name: online_shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: online_shop_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: online_shop

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: online_shop_client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  postgres_data:
